language: java
sudo: required
before_install:
 - wget http://services.gradle.org/distributions/gradle-2.9-bin.zip
 - chmod +x gradlew
 - unzip gradle-2.9-bin.zip
 - export GRADLE_HOME=$PWD/gradle-2.9
 - export PATH=$GRADLE_HOME/bin:$PATH